config/routes.rb
# Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
# http://www.plos.org/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PlosAltMetrics::Application.routes.draw do
  resources :authors
  resources :ratings do
    collection do
      post 'update_spam'
    end
  end

  devise_for :authors, :controllers => { :omniauth_callbacks => "authors/omniauth_callbacks" } do
    get '/authors/auth/:provider' => 'authors/omniauth_callbacks#passthru'
    get 'sign_in', :to => 'authors/sessions#new', :as => :new_author_session
    match 'sign_out', :to => 'authors/sessions#destroy', :as => :destroy_author_session, :via => [:get, :delete]
  end
  
  resources :articles
  #match "/group/articles(/:id)(.:format)" => "groups#groupArticleSummaries"
  
  resources :groups
  resources :citations
  
  # Admin resources
  resources :sources
  resources :categories
  resources :authentications
  get '/docs(/:action)', :controller => :docs, :format => false
  
  get 'about', :to => 'index#index', :as => "about"
  
  # Authors are in default path, should therefore be defined after admin resources. 
  # Root goes to authors#index, needs to be defined.
  resources :posts, :path => "/"
  root :to => "posts#index"

end

app/controllers/articles_controller.rb
# $HeadURL$
# $Id$
#
# Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
# http://www.plos.org/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class ArticlesController < ApplicationController
  before_filter :authenticate_author!, :except => [ :index, :show ]
  before_filter :load_article, 
                :only => [ :edit, :update, :destroy ]
  
  # GET /articles
  # GET /articles.xml
  def index
    # cited=0|1
    # query=(doi fragment)
    # order=doi|published_on (whitelist, default to doi)
    # source=source_type
    unless params[:q].blank?
      @articles = Article.paginate :page => params[:page], 
        :per_page => 10,
        :include => :authors,
        :conditions => ["authors.name REGEXP ? or authors.username REGEXP ? or authors.native_name REGEXP ? or articles.title REGEXP ? or articles.doi REGEXP ?", params[:q], params[:q], params[:q], params[:q], params[:q]]
    else
      collection = Article
      collection = collection.cited(params[:cited])  if params[:cited]
      collection = collection.query(params[:query])  if params[:query]
      collection = collection.order(params[:order])  if params[:order]
      
      if author_signed_in?
        # Fetch all articles by the authors you are following
        @articles = collection.paginate :conditions => ["FIND_IN_SET(contributors.author_id, '?')",current_author.friends], :include => [:authors, :contributors], :page => params[:page], :per_page => 10
      else
        @articles = collection.paginate :page => params[:page], :per_page => 10
      end
    end
    
    @source = Source.find_by_type(params[:source]) if params[:source]

    respond_to do |format|
      format.html do 
        if request.xhr?
          render :partial => "index" 
        end
      end
      format.xml  { render :xml => @articles }
      format.json { render :json => @articles, :callback => params[:callback] }
      format.csv  { render :csv => @articles }
      format.rss { render :rss => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    if params[:refresh] == "now"
      load_article
      Retriever.new(:lazy => false, :only_source => false).update(@article)      
      redirect_to(@article) and return  # why not just keep going with show?
    end

    load_article
    format_options = params.slice :citations, :history, :source

    if params[:refresh] == "soon" or @article.stale?
      uid = RetrievalWorker.async_retrieval(:article_id => @article.id)
      logger.info "Queuing article #{@article.id} for retrieval as #{uid}"
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml do
        response.headers['Content-Disposition'] = 'attachment; filename=' + params[:id].sub(/^info:/,'') + '.xml'
        render :xml => @article.to_xml(format_options)
      end
      format.csv  { render :csv => @article }
      format.json { render :json => @article.to_json(format_options), :callback => params[:callback] }
      format.bib { render :bib => @article }
      format.ris { render :ris => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
      format.json { render :json => @article }
    end
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        flash[:notice] = 'Article was successfully created.'

        Source.all.each do |source|
          Retrieval.find_or_create_by_article_id_and_source_id(@article.id, source.id)
        end    

        format.html { redirect_to(@article) }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
        format.json { render :json => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    
  end
  
  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    respond_to do |format|
      if @article.update_attributes(params[:article])
        flash[:notice] = 'Article was successfully updated.'
        format.html { redirect_to(@article) }
        format.xml  { head :ok }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
      format.json { head :ok }
    end
  end

protected
  def load_article(options={})
    # Load one article given query params, for the non-#index actions
    @article = Article.find_by_short_doi!(params[:id], options)
  end
end

app/helpers/articles_helper.rb
# $HeadURL$
# $Id$
#
# Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
# http://www.plos.org/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module ArticlesHelper
end

app/views/articles/_form.html.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
  # http://www.plos.org/
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<% article ||= form %>
<%= form_for(article.id) do |f| %>
  <p>
    <%= f.label :doi, "DOI" %><br />
    <%= f.text_field :doi %>
  </p>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :published_on %><br />
    <%= date_select 'article', 'published_on', :order => [:month, :day, :year] %>
  </p>
  <p>
    <%= f.submit(article.new_record? ? "Create" : "Update") %>
  </p>
<% end %>

app/views/articles/_index.html.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
  # http://www.plos.org/
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<% unless @articles.empty? %>
	<table class="index">
		<th class="name"><%= pluralize(@articles.total_entries, 'Article') + ((author_signed_in? and params[:q].blank?) ? ' by Authors you are Following' : "") %></th>
		<% active_categories.each do |category| %>
	    <% category.sources.active.each do |source| %>
	      <th class="count">
			    <%= image_tag source.class.to_s.downcase + "_sm.gif", :title => source.category.article_description + ": " + source.name %>
		    </th>
		  <% end %>
    <% end %>
    <% @articles.each do |article| %>
      <tr>
      	<td class="name">	
      	  <span itemprop="name" class="name"><%= link_to article.title, article_path(article.short_doi) %></span><br/>
          <%= formatted_citation(article).html_safe %>
          <% if article.content_type != "journal_article" %>
            <span class="content_type"><%= article.content_type.sub!(/_/, ' ').capitalize %></span>
          <% end %>
          <br/><%= link_to "http://doi.org/" + article.short_doi, "http://doi.org/" + article.short_doi, :itemprop => "url" %>
      	</td>
	      	<% article.citations_by_category.each do |citations| %>  
            <% citations[:sources].each do |citation| %>
    	        <td class="count">
							  <% if citation and citation[:total] > 0 %>
                 <% if citation[:public_url] %>
                   <%= link_to h(citation[:total]), citation[:public_url]  %>
                 <% else %>
                   <%= h(citation[:total]) %>
                 <% end %>
               <% end %>
				    </td>
         <% end %>
   	  <% end %>
	  </tr>
    <% end %>
    <tr>
	    <td class="pagination">
		    <div class="pagination">
			    <%= will_paginate @articles %>
			  </div>
		  </td>
		  <td class="count"></td>
		</tr>
	</table>
  <% else %>
    <h2>No articles found</h2>
  <% end %>

app/views/articles/_show.html.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
  # http://www.plos.org/
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
	<div itemscope itemtype="http://schema.org/ScholarlyArticle">
    <h2><span itemprop="name"><%= @article.title %></span></h2>
		 	<%= formatted_citation(@article).html_safe %>
		  <% if @article.content_type != "journal_article" %>
        <span class="content_type"><%= @article.content_type.sub!(/_/, ' ').capitalize %></span>
      <% end %>
		  <br/><%= link_to "http://doi.org/" + @article.short_doi, "http://doi.org/" + @article.short_doi, :itemprop => "url" %><p>
	</div>

	<div id="source">
    <%= render :partial => 'source'%>
  </div>

  <% if current_author.try(:admin?) %>
    <p>
    Refresh: <%= link_to 'now', article_path(@article.short_doi, :refresh => "now") %> |
    <%= link_to 'soon', article_path(@article.short_doi, :refresh => "soon") %><br/>
    <%= link_to 'Edit', edit_article_path(@article.short_doi) %> |
    <%= link_to 'Delete', article_path(@article.short_doi), :confirm => 'Are you sure?', :method => :delete %>
    <br/>
  <% end %>

app/views/articles/_source.html.erb
<table>
	<% active_categories.each do |category| %>
		<tr>
	    <td class="source_title" colspan="<%= category.sources.active.count %>">
		    <h2><%= h(category.name) %></h2>
		    <%= h(category.article_description) %>
	    </td>
		</tr>
		<tr>
		<% category.sources.active.each do |source| %>
		  <% if source.prefix.blank? or @article.doi.match(/^#{source.prefix}/) %>
		    <td class="source">
		      <%= image_tag source.class.to_s.downcase + ".gif" %>
			  </td>
			<% end %>
	  <% end %>
		</tr>
		<tr>
		    <% category.sources.active.each do |source| %>
		      <% if source.prefix.blank? or @article.doi.match(/^#{source.prefix}/) %>
	      <td class="source_count">
			    <% if @article.citations_by_source(source) and @article.citations_by_source(source)[:public_url] and @article.citations_by_source(source)[:total] > 0 %>
            <%= link_to h(@article.citations_by_source(source)[:total]), @article.citations_by_source(source)[:public_url]  %>
           <% else %>
             <%= @article.citations_by_source(source) ? @article.citations_by_source(source)[:total] : 0 %>
           <% end %>
		    </td>
		    <% end %>
	    <% end %>
		</tr>		
	<% end %>
</table>

app/views/articles/edit.html.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
  # http://www.plos.org/
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<div class="border">
<div class="page">
  <h1>Editing article <%=h @article.doi %></h1>

  <%= render :partial => "form", :object => @article %>

  <%= link_to 'Show', @article %>
  <br/>
  <%= link_to 'Back to list', articles_path %>
</div>
</div>

app/views/articles/index.csv.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
  # http://www.plos.org/
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<% if @source -%>
<%= 
  # Broken out by month for one source
  months = month_range(Date.today, Date.civil((params[:year] || 2009).to_i, 
                                              (params[:month] || 1).to_i, 1))
  this_month = Date.today.at_beginning_of_month
  month_count = months.count
  empty_row = Array.new(month_count, 0)
  FasterCSV.generate do |csv|
    csv << ["DOI", "Published", "Title"] + months.map {|date| "#{date.month}/#{date.year}" }
    @articles.each do |article|
      retrieval = article.retrievals.detect {|r| r.source_id == @source.id }
      month_totals = if retrieval.nil? 
        empty_row
      else
        months.map do |month_date|
          if month_date == this_month
            # special-case current month: use most-recent total, in case we haven't updated this month yet.
            retrieval.total_citations_count
          else
            history = retrieval.histories.detect {|h| h.year == month_date.year && h.month == month_date.month }
            (history && history.citations_count) || 0
          end
        end
      end
      csv << [article.doi, article.published_on, article.title.to_s.strip_tags] + month_totals
    end
  end
-%>
<% else -%>
<%= 
  # Broken out by source, possibly for only a single month
  sources = Source.all.sort_by(&:name)
  one_month = params[:month] && params[:year] && Date.civil(params[:year].to_i, params[:month].to_i, 1)
  this_month = Date.today.at_beginning_of_month if one_month

  FasterCSV.generate do |csv|
    csv << ["DOI", "Published", "Title"] + sources.map(&:name)
    @articles.each do |article|
      source_counts = sources.map do |source|
        retrieval = article.retrievals.detect {|r| r.source_id == source.id }
        if one_month && (one_month != this_month)
          history = retrieval.histories.detect {|h| h.year == one_month.year && h.month == one_month.month } \
            if retrieval
          (history && history.citations_count) || 0
        else
          (retrieval && retrieval.total_citations_count) || 0
        end
      end
      csv << [article.doi, article.published_on, article.title.to_s.strip_tags] + source_counts
    end
  end 
-%>
<% end -%>

app/views/articles/index.html.erb
<%#
  # Copyright (c) 2011 Martin Fenner
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<div id="index">
  <%= render :partial => 'index' %>
</div>

app/views/articles/new.html.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
  # http://www.plos.org/
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<div class="border">
<div class="page">
  <h1>Add a new article</h1>

  <%= render :partial => "form", :object => @article %>

  <%= link_to 'Back to list', articles_path %>
</div>
</div>

app/views/articles/show.bib.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2011 Martin Fenner
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<%= BibTeX::Bibliography.new << @article.to_bib %>

app/views/articles/show.csv.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
  # http://www.plos.org/
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<%=
 FasterCSV.generate do |csv|
    csv << ["article doi", "title", "publish date"]
    csv << [ @article.doi, @article.title, @article.published_on.to_datetime.to_s(:friendly_date) ]
 end
%>
<%= @article.retrievals.map(&:to_csv).join %>

app/views/articles/show.html.erb
<%#
  # Copyright (c) 2011 Martin Fenner
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<div id="show">
  <%= render :partial => 'show' %> 
</div>

app/views/articles/show.ris.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2011 Martin Fenner
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
Provider: ScienceCard
Content:text/plain; charset="UTF-8"

<%= @article.to_ris %>