config/routes.rb
# Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
# http://www.plos.org/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PlosAltMetrics::Application.routes.draw do
  resources :authors
  resources :ratings do
    collection do
      post 'update_spam'
    end
  end

  devise_for :authors, :controllers => { :omniauth_callbacks => "authors/omniauth_callbacks" } do
    get '/authors/auth/:provider' => 'authors/omniauth_callbacks#passthru'
    get 'sign_in', :to => 'authors/sessions#new', :as => :new_author_session
    match 'sign_out', :to => 'authors/sessions#destroy', :as => :destroy_author_session, :via => [:get, :delete]
  end
  
  resources :articles
  #match "/group/articles(/:id)(.:format)" => "groups#groupArticleSummaries"
  
  resources :groups
  resources :citations
  
  # Admin resources
  resources :sources
  resources :categories
  resources :authentications
  get '/docs(/:action)', :controller => :docs, :format => false
  
  get 'about', :to => 'index#index', :as => "about"
  
  # Authors are in default path, should therefore be defined after admin resources. 
  # Root goes to authors#index, needs to be defined.
  resources :posts, :path => "/"
  root :to => "posts#index"

end

app/controllers/authors/omniauth_callbacks_controller.rb
class Authors::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def twitter
    @author = Author.find_for_twitter_oauth(env['omniauth.auth'])

    if @author.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', :kind => 'Twitter'
      @author.remember_me = true
      sign_in_and_redirect @author, :event => :authentication
    else
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.failure', :kind => 'Twitter'
      redirect_to root_path
    end
  end
  
  def google
    raise request.env["omniauth.auth"].to_yaml
  end

  def oauth_mendeley
    raise request.env["omniauth.auth"].to_yaml
  end
  
  def passthru
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end
  
  protected

  # This is necessary since Rails 3.0.4
  # See https://github.com/intridea/omniauth/issues/185
  # and http://www.arailsdemo.com/posts/44
  def handle_unverified_request
    true
  end
  
end

app/controllers/authors/sessions_controller.rb
class Authors::SessionsController < ApplicationController
  def index
  end
  
  def new
  end
  
  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/authors_controller.rb
# Copyright (c) 2011 Martin Fenner
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class AuthorsController < ApplicationController
  before_filter :authenticate_author!, :except => [ :index, :show ]
  before_filter :load_author, 
                :only => [ :edit, :update, :destroy ]

  # GET /authors
  # GET /authors.xml
  def index
    unless params[:q].blank?
      @authors = Author.paginate :page => params[:page], 
        :per_page => 12,
        :conditions => ["authors.name REGEXP ? or authors.username REGEXP ? or authors.native_name REGEXP ? or authors.mas REGEXP ?", params[:q],params[:q],params[:q],params[:q]]
    else
      @authors = Author.paginate :page => params[:page], :per_page => 12
    end
    
    respond_to do |format|
      format.html do 
        if request.xhr?
          render :partial => "index" 
        end
      end
      format.xml  { render :xml => @authors }
      format.json { render :json => @authors, :callback => params[:callback] }
      format.csv  { render :csv => @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.xml
  def show
    load_author
    @articles = @author.articles.paginate :page => params[:page], :per_page => 10, :include => :retrievals, :order => "IF(articles.published_on IS NULL, articles.year, articles.published_on) desc"
    
    respond_to do |format|
      format.html 
      format.js { render "show" }
      format.xml do
        response.headers['Content-Disposition'] = 'attachment; filename=' + params[:id].sub(/^info:/,'') + '.xml'
        render :xml => @author.articles.to_xml
      end
      format.csv  { render :csv => @author }
      format.json { render :json => @author.to_json, :callback => params[:callback] }
      format.bib { render :bib => @author }
      format.ris { render :ris => @author }
      format.rss { render :rss => @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.xml
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @author }
      format.json { render :json => @author }
    end
  end
  
  # GET /authors/1/edit
  def edit
    @articles = @author.articles.paginate :page => params[:page], :per_page => 10, :order => "IF(articles.published_on IS NULL, articles.year, articles.published_on) desc"
    
    respond_to do |format|
      format.js { render "show" }
    end
  end

  # POST /authors
  # POST /authors.xml
  def create
    # Get author if it exists, otherwise create new one
    #@author = Author.find_or_initialize_by_mas(:mas  => params[:author][:mas])

    #respond_to do |format|
    #  if @author.save
    #    # Fetch author information and update author
    #    properties = Author.fetch_properties(@author)
    #    @author = Author.update_properties(@author, properties)
    #    flash[:notice] = 'Author was successfully created.' if @author.new_record?
    
    #    format.html { redirect_to author_path(@author.mas, :format => :html) }
    #    format.xml  { render :xml => @author, :status => :created, :location => @author }
    #    format.json { render :json => @author, :status => :created, :location => @author }
    #  else
    #    format.html { render :action => "new" }
    #    format.xml  { render :xml => @author.errors, :status => :unprocessable_entity }
    #    format.json { render :json => @author.errors, :status => :unprocessable_entity }
    #  end
    #end
  end

  # PUT /authors/1
  # PUT /authors/1.xml
  def update
    @articles = @author.articles.paginate :page => params[:page], :per_page => 10, :order => "IF(articles.published_on IS NULL, articles.year, articles.published_on) desc"
  
    respond_to do |format|
      if @author.update_attributes(params[:author])
        if params[:service] == "mas"
          # First remove all mas article claims, e.g. because Microsoft Academic Search ID was changed or set to empty 
          @author.contributors.where(:service => "mas").each do |contributor|
            contributor.update_attributes(:author_id => nil)
          end
          
          # Fetch articles from author, return nil if no response
          results = Author.fetch_articles_from_mas(@author)
          
          unless results.empty?
            results.each do |result|
              # Only add articles with DOI and title
              unless result["DOI"].nil? or result["Title"].nil?
                #result["DOI"] = DOI::clean(result["DOI"])
                article = Article.find_or_create_by_doi(:doi => result["DOI"], :title => result["Title"])
                article.save
                # Check that DOI is valid
                if article.valid?
                  article.update_attributes(:mas => result["ID"])
                  result["Author"].each do |author|
                    contributor = Contributor.find_or_create_by_article_id_and_mas_and_service(:article_id => article.id,
                                                            :mas => author["ID"],
                                                            :service => "mas",
                                                            :surname => author["LastName"],
                                                            :given_name => author["FirstName"]) 
                    contributor.update_attributes(:author_id => @author.id) if (author["ID"].to_s == @author.mas)
                  end
                  Article.update_via_crossref(article)
                end
              end
            end
          end
        elsif params[:service] == "authorclaim"
          # First remove all authorclaim article claims, e.g. because AuthorClaim ID was changed or set to empty
          @author.contributors.where(:service => "authorclaim").each do |contributor|
            contributor.update_attributes(:author_id => nil)
          end
          
          # Fetch articles from author, return nil if no response
          results = Author.fetch_articles_from_authorclaim(@author)
          
          unless results.blank?
            results[:articles].each do |result|
              # Only add articles with DOI and title
              unless result["DOI"].nil? or result["Title"].nil?
                #result["DOI"] = DOI::clean(result["DOI"])
                article = Article.find_or_create_by_doi(:doi => result["DOI"], :title => result["Title"])
                article.save
                # Check that DOI is valid
                if article.valid?
                  contributor = Contributor.create(:article_id => article.id,
                                                          :author_id => @author.id,
                                                          :surname => results[:contributor]["surname"],
                                                          :given_name => results[:contributor]["given_name"],
                                                          :service => "authorclaim",
                                                          :authorclaim => @author.authorclaim)
                end
                Article.update_via_crossref(article)
              end
            end
          end
        elsif params[:service] == "scopus"
          # First remove all scopus article claims, e.g. because Scopus Author ID was changed or set to empty 
          @author.contributors.where(:service => "scopus").each do |contributor|
            contributor.update_attributes(:author_id => nil)
          end

          # Fetch articles from author, return nil if no response
          results = Author.fetch_articles_from_scopus(@author)

          unless results.empty?
            results.each do |result|
              # Only add articles with DOI and title
              unless result["DOI"].nil? or result["Title"].nil?
                #result["DOI"] = DOI::clean(result["DOI"])
                article = Article.find_or_create_by_doi(:doi => result["DOI"], :title => result["Title"])
                article.save
                # Check that DOI is valid
                if article.valid?
                  article.update_attributes(:scopus => result["ID"])
                  result["Author"].each do |author|
                    contributor = Contributor.find_or_create_by_article_id_and_scopus_and_service(:article_id => article.id,
                                                            :scopus => author["ID"],
                                                            :service => "scopus",
                                                            :surname => author["LastName"],
                                                            :given_name => author["FirstName"]) 
                    contributor.update_attributes(:author_id => @author.id) if (author["ID"].to_s == @author.mas)
                  end
                  Article.update_via_crossref(article)
                end
              end
            end
          end
        elsif params[:service] == "twitter"
          Author.update_via_twitter(@author)
        end
        #flash[:notice] = 'Author was successfully updated.'
        format.js { render "show" }
        format.html do
          if request.xhr? 
            render :update do |page|
              unless @author.image.blank?
                page.replace 'photo', '<div id="photo"><img alt="' + @author.username + '" class="photo" src="' + @author.image + '" /></div'
              else
                page.replace 'photo', '<div id="photo"></div'
              end

app/views/authors/_article.html.erb
<%#
  # Copyright (c) 2011 Martin Fenner
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>

<% unless @author.articles.empty? %>
	<% unless active_categories.empty? %>
	  <div id="source">
	    <%= render :partial => 'source'%>
	  </div>
	<% end %>
	<p>

	<div class="article">
		<table>
			<th class="name">
				<h2><%= pluralize(@author.articles.count, 'Article') %></h2>
			</th>
			<% active_categories.each do |category| %>
		    <% category.sources.active.each do |source| %>
		      <th class="count">
				    <%= image_tag source.class.to_s.downcase + "_sm.gif", :title => source.category.article_description + ": " + source.name %>
			    </th>
			  <% end %>
	    <% end %>
	    <% @articles.each do |article| %>
	      <tr>
	      	<td class="name">	
	      	  <span itemprop="name" class="name"><%= link_to article.title, article_path(article.short_doi) %></span><br/>
	          <%= formatted_citation(article).html_safe %>
	          <% if article.content_type != "journal_article" %>
	            <span class="content_type"><%= article.content_type.sub!(/_/, ' ').capitalize %></span>
	          <% end %>
	          <br/><%= link_to "http://doi.org/" + article.short_doi, "http://doi.org/" + article.short_doi, :itemprop => "url" %>
	      	</td>
	          <% active_categories.each do |category| %>
					    <% category.sources.active.each do |source| %>
				        <td class="count">
					        <% citation = article.citations_by_source(source) %>
								  <% if citation and citation[:total] > 0 %>
	                 <% if citation[:public_url] %>
	                   <%= link_to h(citation[:total]), citation[:public_url]  %>
	                 <% else %>
	                   <%= h(citation[:total]) %>
	                 <% end %>
	               <% end %>
					    </td>
				    <% end %>
	   	  <% end %>
		  </tr>
	    <% end %>
			<tr>
		    <td class="pagination">
			    <div class="pagination">
				    <%= will_paginate @articles %>
				  </div>
			  </td>
			  <td class="count"></td>
			</tr>
		</table>
	</div>
<% else %>
  <% unless @author.mas.blank? %>
    <h3>No articles found</h3>
  <% end %>
<% end %>

app/views/authors/_googlescholar.html.erb
<% if params[:service] == "googlescholar" and ((controller.action_name == "edit" or (controller.action_name == "update" and !@author.errors.empty?))) %>
  <div class="edit">
	  <%= remote_form_for :author, :update => "service", :url => author_url(:id => @author.username, :partial => "service", :service => "googlescholar"), :method => :put do |f| %>
    <h3>Google Scholar</h3>
		    <%= f.text_field :googlescholar %>
		  <p>
			  <%= link_to_remote "Cancel", :update => "service", :url => author_path(@author.username, :partial => "service"), :method => :get %>
		    <%= f.submit("Submit") %>
		<% end %>
	</div>
<% else %>
	  <%= image_tag "googlescholar.png", :class => "photo_mini", :title => "Mendeley" %><br/>
		<span class="name"><%= @author.googlescholar.blank? ? "not set" : link_to(@author.googlescholar, "http://scholar.google.com/citations?user=" + @author.googlescholar) %></span>
		<% if current_author == @author or current_author.try(:admin?) %>&nbsp;<%= link_to_remote image_tag("edit.gif"), { :update => "service", 
		                                       :url => edit_author_path(@author.username, :partial => "service", :service => "googlescholar"),
		                                       :method => :get },
		                                       :title => "Edit Google Scholar" %>
		<% end %>
<% end %>

app/views/authors/_index.html.erb
<%#
  # Copyright (c) 2011 Martin Fenner
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%> 
<% unless @authors.empty? %>
  <table class="index">
	  <th class="name"><%= pluralize(@authors.total_entries, 'User') %></th>
	<% @authors.in_groups_of(2, false) do |authors| %> 
	  <tr>  
	    <% authors.each do |author| %>  
	    	<td class="index">
		      <% unless author.nil? %>
						<%= image_tag "http://api.twitter.com/1/users/profile_image/#{author.username}", :class => "photo_mini" %>
	      	  <span class="name"><%= link_to author.display_name, author_path(author.username) %></span><br/>
	          <%= link_to "@#{author.username}", "http://twitter.com/#{author.username}" %><br />
	          <%= pluralize(author.ratings_count, 'Rating') %>
	        <% end %>
      	</td>
	    <% end %>  
	  </tr>  
	<% end %>
	<tr>
    <td class="pagination" colspan=2>
		  <%= will_paginate @authors %>
	  </td>
	</tr>
	</table>
<% else %>
	<h2>Welcome to CrowdoMeter</h2>
<% end %>

app/views/authors/_mas.html.erb
<% if params[:service] == "mas" and (controller.action_name == "edit" or (controller.action_name == "update" and !@author.errors.empty?)) %>
  <div class="edit">
	  <%= form_for :author, :url => author_url(:id => @author.username, :partial => "service", :service => "mas"), :remote => true, :method => :put do |f| %>
	  <h3>Microsoft Academic Search</h3>
    <% if mas_choices(@author).nil? or mas_choices(@author).empty? %>
      <%= f.text_field :mas %>
    <% else %>
      <%= f.select(:mas, mas_choices(@author), :include_blank => 'None', :prompt => 'Please Select:') %>
    <% end %>
		  <p>
			  <%= link_to "Cancel", :url => author_path(@author.username, :partial => "service"),:remote => true, :method => :get %>
		    <%= f.submit("Submit") %>
		    <%= image_tag 'spinner.gif', :id=>'spinner', :style=>"display:none;" %>
		<% end %>
	</div>
<% else %>
	  <%= image_tag "mas.png", :class => "photo_mini", :title => "Microsoft Academic Search" %><br/>
		<span class="name"><%= @author.mas.blank? ? "not set" : link_to(@author.mas, "http://academic.research.microsoft.com/Author/" + @author.mas) %></span>
		<% if current_author == @author or current_author.try(:admin?) %>&nbsp;<%= link_to_remote image_tag("edit.gif"), { :update => "service", 
		                                       :url => edit_author_path(@author.username, :partial => "service", :service => "mas"),
		                                       :method => :get },
		                                       :title => "Edit Microsoft Academic Search" %>
		<% end %>
<% end %>

app/views/authors/_mendeley.html.erb
<% if params[:service] == "mendeley" and ((controller.action_name == "edit" or (controller.action_name == "update" and !@author.errors.empty?))) %>
  <div class="edit">
	  <%= remote_form_for :author, :update => "service", :url => author_url(:id => @author.username, :partial => "service", :service => "mendeley"), :method => :put do |f| %>
    <h3>Mendeley</h3>
		    <%= f.text_field :mendeley %>
		  <p>
			  <%= link_to_remote "Cancel", :update => "service", :url => author_path(@author.username, :partial => "service"), :method => :get %>
		    <%= f.submit("Submit") %>
		<% end %>
	</div>
<% else %>
	  <%= image_tag "mendeley.png", :class => "photo_mini", :title => "Mendeley" %><br/>
		<span class="name"><%= @author.mendeley.blank? ? "not set" : link_to(@author.mendeley, "http://www.mendeley.com/profiles/" + @author.mendeley) %></span>
		<% if current_author == @author or current_author.try(:admin?) %>&nbsp;<%= link_to_remote image_tag("edit.gif"), { :update => "service", 
		                                       :url => edit_author_path(@author.username, :partial => "service", :service => "mendeley"),
		                                       :method => :get },
		                                       :title => "Edit Mendeley" %>
		<% end %>
<% end %>

app/views/authors/_profile.html.erb
<table class="profile">
	<tr>
		<td class="photo">
			<div id="photo">
				<% unless @author.image.blank? %>
	        <%= image_tag @author.image, :class => "photo" %>
	      <% end %>
	    </div>
	  </td>
		<td class="twitter">
	    <div id="twitter">
	      <%= render :partial => 'twitter' %>
	    </div>
	  </td>
	  <td class="service">
		  <div id="service">
	      <%= render :partial => 'service' %>
	    </div>
	  </td>
	</tr>
</table>

app/views/authors/_scopus.html.erb
<% if params[:service] == "scopus" and ((controller.action_name == "edit" or (controller.action_name == "update" and !@author.errors.empty?))) %>
  <div class="edit">
	  <%= remote_form_for :author, :update => "service", :url => author_url(:id => @author.username, :partial => "service", :service => "scopus"), :before => "Element.show('spinner');", :method => :put do |f| %>
    <h3>Scopus Author ID</h3>
		    <%= f.text_field :scopus %>
		  <p>
			  <%= link_to_remote "Cancel", :update => "service", :url => author_path(@author.username, :partial => "service"), :method => :get %>
		    <%= f.submit("Submit") %>
		    <%= image_tag 'spinner.gif', :id=>'spinner', :style=>"display:none;" %>
		<% end %>
	</div>
<% else %>
	  <%= image_tag "scopus.png", :class => "photo_mini", :title => "Scopus" %><br/>
		<span class="name"><%= @author.scopus.blank? ? "not set" : link_to(@author.scopus, "http://scopus.org/profile/" + @author.scopus) %></span>
		<% if current_author == @author or current_author.try(:admin?) %>&nbsp;<%= link_to_remote image_tag("edit.gif"), { :update => "service", 
		                                       :url => edit_author_path(@author.username, :partial => "service", :service => "scopus"),
		                                       :method => :get },
		                                       :title => "Edit Scopus" %>
		<% end %>
<% end %>

app/views/authors/_service.html.erb
<% unless (controller.action_name == "edit" or (controller.action_name == "update" and !@author.errors.empty?)) and ["mendeley", "mas", "authorclaim", "scopus","googlescholar"].include?(params[:service]) %>
	<div class="service">
	  <%= image_tag "twitter.png", :class => "photo_mini", :title => "Twitter" %><br/>
	  <span class="name"><%= link_to "@#{@author.username}", "http://twitter.com/" + @author.username %></span>
	</div>
<% end %>

app/views/authors/_source.html.erb
<table>
	<% active_categories.each do |category| %>
	<tr>
	    <td class="source_title" colspan="<%= category.sources.active.count %>">
		    <h2><%= h(category.name) %></h2>
		    <%= h(category.author_description) %>
	    </td>
	</tr>
	<tr>
	    <% category.sources.active.each do |source| %>
	      <td class="source">
			    <%= image_tag source.class.to_s.downcase + ".gif" %>
		    </td>
		  <% end %>
	</tr>
	<tr>
		    <% category.sources.active.each do |source| %>
	      <td class="source_count">
			    <%= @author.citations_count(source) %>
		    </td>
	    <% end %>
	</tr>	
  <% end %>
</table>

app/views/authors/_twitter.html.erb
<% if params[:partial] == "twitter" and ((controller.action_name == "edit" or (controller.action_name == "update" and !@author.errors.empty?))) %>
  <div class="edit">
	  <div class="profile">
			<%= form_for :author, :url => author_url(@author.username, :partial => "twitter", :service => "twitter"), :html => { :method => :put, :remote => true } do |f| %>
			  <h3>Name</h3>
			  <%= f.text_field :name, :class => :name %><p>
				<%= link_to "Cancel", author_path(@author.username, :partial => "twitter"), :remote => true %>
			  <%= f.submit("Submit") %>
			  <%= image_tag 'spinner.gif', :id=>'spinner', :style=>"display:none;" %>
			<% end %>
		</div>
	</div>
<% else %>
	<h2>
		<%= h(@author.display_name) %>
		<% if current_author == @author or current_author.try(:admin?) %>
			<%= link_to image_tag("edit.gif"), edit_author_path(@author.username, :partial => "twitter"), :remote => true, :title => "Edit Name" %>
		<% end %>
	</h2>
	<% unless @author.location.blank? %>
		<%= @author.location %>
	<% end %>
	<p>
	<% unless @author.description.blank? %>
		<%= @author.description %><br/>
	<% end %>
	<% unless @author.website.blank? %>
		<%= link_to @author.website, @author.website %>
	<% end %>
<% end %>

app/views/authors/index.html.erb
<%#
  # Copyright (c) 2011 Martin Fenner
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<div id="index">
  <%= render :partial => 'index' %> 
</div>

app/views/authors/show.csv.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
  # http://www.plos.org/
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<%=
 FasterCSV.generate do |csv|
    csv << ["author doi", "title", "publish date"]
    csv << [ @author.doi, @author.title, @author.published_on.to_datetime.to_s(:friendly_date) ]
 end
%>
<%= @author.retrievals.map(&:to_csv).join %>

app/views/authors/show.html.erb
<%#
  # Copyright (c) 2011 Martin Fenner
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<div id="show">
	<%= render :partial => 'show'%>
</div>

app/views/authors/show.js.erb
<% if params[:partial] == "twitter" %>
  $('#twitter').html("<%= escape_javascript(render "twitter") %>");
<% else %>
  $('#profile').html("<%= escape_javascript(render "profile") %>");
<% end %>