config/routes.rb
# Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
# http://www.plos.org/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PlosAltMetrics::Application.routes.draw do
  resources :authors
  resources :ratings do
    collection do
      post 'update_spam'
    end
  end

  devise_for :authors, :controllers => { :omniauth_callbacks => "authors/omniauth_callbacks" } do
    get '/authors/auth/:provider' => 'authors/omniauth_callbacks#passthru'
    get 'sign_in', :to => 'authors/sessions#new', :as => :new_author_session
    match 'sign_out', :to => 'authors/sessions#destroy', :as => :destroy_author_session, :via => [:get, :delete]
  end
  
  resources :articles
  #match "/group/articles(/:id)(.:format)" => "groups#groupArticleSummaries"
  
  resources :groups
  resources :citations
  
  # Admin resources
  resources :sources
  resources :categories
  resources :authentications
  get '/docs(/:action)', :controller => :docs, :format => false
  
  get 'about', :to => 'index#index', :as => "about"
  
  # Authors are in default path, should therefore be defined after admin resources. 
  # Root goes to authors#index, needs to be defined.
  resources :posts, :path => "/"
  root :to => "posts#index"

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  
  belongs_to :post, :counter_cache => true
  belongs_to :author, :counter_cache => true
  
  validates_uniqueness_of :post_id, :scope => :author_id
  
  attr_accessible :post_id, :author_id, :rhetoric, :spam, :is_author, :method, :data, :conclusions, :topic
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  
  # GET /ratings
  # GET /ratings.xml
  def index
    @ratings = Rating.all
    @posts_with_ratings = Post.where('ratings_count > 0')
    @posts = Post.where(:content_type => 'tweet').order(:published_at)
    @posts_with_rts = Post.find(:all, :conditions => "body REGEXP '^RT[[:space:]]'")
    @posts_with_spam = Post.find(:all, :conditions => "ratings.spam = 1", :include => :ratings)
    @posts_with_topic = Post.joins(:ratings).where("ratings.topic IS NOT NULL")
    @posts_with_title = Post.find(:all, :conditions => "body REGEXP IF(LENGTH(article_title) < 20, article_title, LEFT(article_title, 20))")
    @unique_author_count = Post.count(:author, :distinct => true)
    @unique_article_count = Post.count(:article_title, :distinct => true)
    @unique_journal_count = Post.count(:journal_title, :distinct => true)
    @authors = Author.order('ratings_count desc').limit(10)
    @authors_with_ratings = Author.all
    
    # Create pie chart for subject area
    topic_names = ["Medicine & Health", "Life Sciences", "Physics & Astronomy", "Chemistry & Materials Science", "Earth Sciences", "Social Sciences & Economics", "Computer Science & Math", "Other"]
    topics = []
    topic_names.each_with_index do |item, index|
      topics << Post.joins(:ratings).where(:ratings => { :topic => item })
    end
    
    @topicchart = LazyHighCharts::HighChart.new('pie') do |f|
      f.chart({ :defaultSeriesType=>"pie", :marginLeft => 70, :marginRight => 70, :backgroundColor => nil } )
      f.series(:name => "Tweets", :data => [{ :name => topic_names[0], :y => topics[0].count, :color => "#F7FCF5" }, 
                                            { :name => topic_names[1], :y => topics[1].count, :color => "#E5F5E0"}, 
                                            { :name => topic_names[2], :y => topics[2].count, :color => "#C7E9C0"},
                                            { :name => topic_names[3], :y => topics[3].count, :color => "#A1D99B"},
                                            { :name => topic_names[4], :y => topics[4].count, :color => "#74C476"},
                                            { :name => topic_names[5], :y => topics[5].count, :color => "#41AB5D"},
                                            { :name => topic_names[6], :y => topics[6].count, :color => "#238B45"},
                                            { :name => topic_names[7], :y => topics[7].count, :color => "#006D2C"}])
      f.options[:title][:text] = nil
    end
    
    # Create pie chart for rhetoric
    rhetoric = Rating.order('rhetoric').group("rhetoric").count
    @posts_with_agreement = Post.find(:all, :conditions => "ratings.rhetoric = 'agreesWith'", :include => :ratings)
    @posts_with_disagreement = Post.find(:all, :conditions => "ratings.rhetoric = 'disagreesWith'", :include => :ratings)
    @rhetoricchart = LazyHighCharts::HighChart.new('pie') do |f|
      f.chart({ :defaultSeriesType=>"pie", :marginLeft => 70, :marginRight => 70, :backgroundColor => nil } )
      f.series(:name => "Tweets", :data => [{ :name => "agrees with", :y => @posts_with_agreement.count, :color => "#41AB5D" }, { :name => "disagrees with", :y => @posts_with_disagreement.count, :color => "#A1D99B"}, { :name => "discusses", :y => @posts_with_ratings.count - (@posts_with_agreement.count + @posts_with_disagreement.count), :color => "#F7FCF5"} ])
      f.options[:title][:text] = nil
    end
    
    # Create pie chart for posts from author/publisher
    @posts_with_authors = Post.find(:all, :conditions => "ratings.is_author = 1", :include => :ratings) 
    @authorchart = LazyHighCharts::HighChart.new('pie') do |f|
      f.chart({:defaultSeriesType=>"pie", :marginLeft => 70, :marginRight => 70, :backgroundColor => nil } )
      f.series(:name => "Tweets", :data => [{ :name => "Author/Publisher", :y => @posts_with_authors.count, :color => "#41AB5D" }, { :name => "Other", :y => @posts_with_ratings.count - @posts_with_authors.count, :color => "#F7FCF5" }])
      f.options[:title][:text] = nil
    end
    
    # Create bar chart for using methods/data/conclusions
    @posts_with_method = Post.find(:all, :conditions => "ratings.method = 1", :include => :ratings) 
    @posts_with_data = Post.find(:all, :conditions => "ratings.data = 1", :include => :ratings)
    @posts_with_conclusions = Post.find(:all, :conditions => "ratings.conclusions = 1", :include => :ratings)
    @reusechart = LazyHighCharts::HighChart.new('chart') do |f|
      f.chart({:defaultSeriesType=>"column", :height => 250, :backgroundColor => nil } )
      f.series(:name => "Tweets", :color => "#41AB5D", :data => [@posts_with_method.count, @posts_with_data.count, @posts_with_conclusions.count], :colors => ["#41AB5D", "#A1D99B", "#F7FCF5"])
      f.options[:xAxis] = { :categories => ['Methods', 'Data', 'Conclusions'], :tickLength => 0, :lineColor => "#000000" }
      f.options[:yAxis] = { :max => @posts_with_ratings.count, :lineWidth => 1, :lineColor => "#000000", :gridLineWidth => 0, :title => nil, :labels  => { :enabled => true }, :tickInterval => @posts_with_ratings.count, :showFirstLabel => false }
      f.options[:title][:text] = nil
      f.options[:plotOptions] = { :column => { :borderWidth => 0 } }
      f.options[:legend] = false
    end 
    
    # Calculate rating activity by day
    days = Rating.order('created_at').group('DATE(created_at)').count
    @activitychart = LazyHighCharts::HighChart.new('chart') do |f|
      f.chart({:defaultSeriesType=>"spline", :height => 150, :marginRight => 30, :backgroundColor => nil } )
      f.series(:name => "Ratings", :color => "#41AB5D", :data => days.map {|a| [a[0].to_time.utc.to_i * 1000, a[1]] })
      f.options[:xAxis] = { :type => 'datetime', :tickLength => 0, :lineColor => "#000000", :labels  => { :enabled => true } }
      f.options[:yAxis] = { :min => 0, :max => @posts_with_ratings.count, :lineWidth => 1, :lineColor => "#000000", :gridLineWidth => 0, :title => nil, :labels  => { :enabled => true }, :tickInterval => @posts_with_ratings.count, :showFirstLabel => false }
      f.options[:title][:text] = nil
      f.options[:legend] = false
      f.options[:plotOptions] = { :column => { :connectNulls => true } }
    end
      
    respond_to do |format|
      format.html # index.html.erb
      format.mobile # index.mobile.erb
      format.json # index.mobile.erb
      format.csv # index.csv.erb
    end
  end

  # GET /ratings/1
  # GET /ratings/1.xml
  def show
    @rating = Rating.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rating }
    end
  end

  # GET /ratings/new
  # GET /ratings/new.xml
  def new
    @post = Post.find(params[:post_id])
    @rating = Rating.find_or_initialize_by_id(params[:id], :rhetoric => "discusses") 

    respond_to do |format|
      format.html
      format.mobile # new.mobile.erb
    end
  end

  # GET /ratings/1/edit
  def edit
    @rating = Rating.find(params[:id])
  end

  # POST /ratings
  # POST /ratings.xml
  def create
    if params[:format] == "mobile"
      # Workaround because we have to use check_box_tag
      params[:rating][:spam] = params[:rating][:spam] || 0
      params[:rating][:is_author] = params[:rating][:is_author] || 0
      params[:rating][:method] = params[:rating][:method] || 0
      params[:rating][:data] = params[:rating][:data] || 0
      params[:rating][:conclusions] = params[:rating][:conclusions] || 0
    end
    
    @post = Post.find(params[:rating][:post_id])
    @rating = Rating.new(params[:rating])
    @rating.save
    
    if !params[:q].blank?
      if params[:q] == "I'm feeling lucky"
        @posts = Post.paginate :page => params[:page], 
           :per_page => 4,
           :conditions => ["posts.ratings_count IS NULL OR posts.id NOT IN (SELECT post_id FROM ratings WHERE author_id = ?)", author_signed_in? ? current_author.id : 0],
           :include => :ratings,
           :order => 'RAND(DAYOFYEAR(NOW()))'
      else
        @posts = Post.paginate :page => params[:page], 
          :per_page => 25,
          :conditions => ["CONCAT(posts.body,posts.author) REGEXP ?", params[:q]],
          :order => 'RAND(DAYOFYEAR(NOW()))'
      end
    elsif params[:format] == "mobile"
      @posts = Post.find(:all, :conditions => ["posts.ratings_count IS NULL OR posts.id NOT IN (SELECT post_id FROM ratings WHERE author_id = ?)", author_signed_in? ? current_author.id : 0], :include => :ratings, :order => 'RAND(DAYOFYEAR(NOW()))', :limit => 10)
    else
      @posts = Post.where(:content_type => 'tweet').order('RAND(DAYOFYEAR(NOW()))').paginate(:page => params[:page], :per_page => 25)
    end
    
    respond_to do |format|
      format.js { render "posts/index" }
      format.html { render "posts/index"}
      format.mobile { render "posts/index"}
    end
  end

  # PUT /ratings/1
  # PUT /ratings/1.xml
  def update
    unless params[:q].blank?
      if params[:q] == "I'm feeling lucky"
        @posts = Post.paginate :page => params[:page], 
           :per_page => 4,
           :conditions => ["posts.ratings_count IS NULL OR posts.id NOT IN (SELECT post_id FROM ratings WHERE author_id = ?)", author_signed_in? ? current_author.id : 0],
           :include => :ratings,
           :order => 'RAND(DAYOFYEAR(NOW()))'
      else
        @posts = Post.paginate :page => params[:page], 
          :per_page => 25,
          :conditions => ["CONCAT(posts.body,posts.author) REGEXP ?", params[:q]],
          :order => 'RAND(DAYOFYEAR(NOW()))'
      end
    else
      @posts = Post.where(:content_type => 'tweet').order('RAND(DAYOFYEAR(NOW()))').paginate(:page => params[:page], :per_page => 25)
    end
    @rating = Rating.find(params[:id])
    @post = @rating.post
    @rating.update_attributes(params[:rating])
    
    respond_to do |format|
      format.js { render "posts/index" }
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.xml
  def destroy

app/helpers/ratings_helper.rb
module RatingsHelper
  def page_title
    "Results"
  end
end

app/views/ratings/_edit.html.erb
<tr id="post_<%= @post.id %>">
	<td class="name">
		<div class="edit">
      <%= image_tag "http://api.twitter.com/1/users/profile_image/#{@post.author}", :class => "photo_mini" %>
      <div class="body">
	      <span class="name"><%= link_to "@#{@post.author}", @post.author_with_link %></span>
	      <span class="date"><%= l @post.published_at, :format => :twitter %></span><br />
	      <%= @post.body_with_links.html_safe %>
		  </div>
		  <div class="cito">
			  <% form_for(@rating, :url => rating_url(:id => @rating, :page => params[:page], :q => params[:q]), :remote => true) do |form| %>
				  <% unless @post.article_title.blank? %>
			      <%= @post.article_title_and_journal.html_safe %><p>
				  <% end %>
          <%= render :partial => 'ratings/form', :locals => { :form => form } %>
	      <% end %>
	    </div>
	  </div>
  </td>
  <%= render :partial => 'posts/rating', :locals => { :post => @post } %>
</tr>

app/views/ratings/_form.html.erb
<%= form.check_box(:spam) %> Spam. The tweet contains text and/or links unrelated to the linked scholarly article.<p>
<div id="cito" style="<%= @rating.spam ? 'display: none;' : '' %>">
	<div class="select">
	  Subject Area: <%= form.select :topic, topic_choices, { :prompt => 'Select' } %>
	</div>
	<%= form.radio_button("rhetoric", "agreesWith") %> Agrees with statements, ideas or conclusions presented in the cited paper. Positive sentiment, e.g. "great work!". (<%= link_to "cito:agreesWith", "http://speroni.web.cs.unibo.it/cgi-bin/lode/req.py?req=http:/purl.org/spar/cito#d3e72" %>)<br />
		<%= form.radio_button("rhetoric", "discusses") %> Discusses statements, ideas or conclusions presented in the cited paper. Neutral or simply mentioning an article. (<%= link_to "cito:discusses", "http://speroni.web.cs.unibo.it/cgi-bin/lode/req.py?req=http:/purl.org/spar/cito#d3e274" %>)<br />
		<%= form.radio_button("rhetoric", "disagreesWith") %> Disagrees with statements, ideas or conclusions presented in the cited paper. Negative sentiment, e.g. "ridiculous paper". (<%= link_to "cito:disagreesWith", "http://speroni.web.cs.unibo.it/cgi-bin/lode/req.py?req=http:/purl.org/spar/cito#d3e261" %>)<p>
		<%= form.check_box(:is_author) %> Written by an author or publisher of the cited paper. The tweeter was involved with the article mentioned. Don't include RTs by others. (<%= link_to "cito:sharesAuthorsWith", "http://speroni.web.cs.unibo.it/cgi-bin/lode/req.py?req=http:/purl.org/spar/cito#d3e980" %>)<p>
		<%= form.check_box(:method) %> Describes a method detailed in the cited paper. Also description of study subjects, e.g. "A study of 10,000 runners found". (<%= link_to "cito:usesMethodIn", "http://speroni.web.cs.unibo.it/cgi-bin/lode/req.py?req=http:/purl.org/spar/cito#d3e1051" %>)<br />
		<%= form.check_box(:data) %> Uses data presented in the cited paper. This should usually be actual numbers, e.g. "smokers die 25 years sooner". (<%= link_to "cito:usesDataFrom", "http://speroni.web.cs.unibo.it/cgi-bin/lode/req.py?req=http:/purl.org/spar/cito#d3e1037" %>)<br />
		<%= form.check_box(:conclusions) %> Describes conclusions presented in the cited paper, e.g. "humanity is getting less violent". (<%= link_to "cito:usesConclusionsFrom", "http://speroni.web.cs.unibo.it/cgi-bin/lode/req.py?req=http:/purl.org/spar/cito#d3e1022" %>)<p>
</div>

<div class="submit">
  <%= link_to "Cancel", posts_path(:page => params[:page], :q => params[:q]), :remote => true %>
  <%= form.submit("Submit") %>
</div>

app/views/ratings/_new.html.erb
<tr id="post_<%= @post.id %>">
	<td class="name">
		<div class="edit">
      <%= image_tag "http://api.twitter.com/1/users/profile_image/#{@post.author}", :class => "photo_mini" %>
      <div class="body">
	      <span class="name"><%= link_to "@#{@post.author}", @post.author_with_link %></span>
	      <span class="date"><%= l @post.published_at, :format => :twitter %></span><br />
	      <%= @post.body_with_links.html_safe %>
		  </div>
		  <div class="cito">
			  <% form_for(@rating, :url => ratings_url(:page => params[:page], :q => params[:q]), :remote => true) do |form| %>
			    <% unless @post.article_title.blank? %>
				    <%= @post.article_title_and_journal.html_safe %><p>
			    <% end %>
		      <%= form.hidden_field :post_id, :value => @post.id %>
		      <%= form.hidden_field :author_id, :value => current_author.id %>
          <%= render :partial => 'ratings/form', :locals => { :form => form } %>
	      <% end %>
	  	</div>
	  </div>
  </td>
  <%= render :partial => 'posts/rating', :locals => { :post => @post } %>
</tr>

app/views/ratings/index.csv.erb
<%=
  FasterCSV.generate do |csv|
	  # header row 
    csv << [ "id", "post_id", "rating_author", "rating_date", "tweet_id", "tweet_author","is_spam", "topic", "shares_author", "rhetoric", "uses_method", "uses_data", "uses_conclusions" ]
    # data rows
    @ratings.each do |rating|
      csv << [ rating.id, rating.post_id, rating.author.username, rating.updated_at.to_datetime.to_s(:friendly_date), rating.post.original_id, rating.post.author, rating.spam, rating.topic.blank? ? nil : rating.topic, rating.is_author, rating.rhetoric, rating.method, rating.data, rating.conclusions ]
    end
  end
%>

app/views/ratings/index.html.erb
<div id="index">
  <%= render :partial => 'index' %>
</div>

app/views/ratings/index.mobile.erb
<div data-role="header">
	<%= link_to 'Tweets', posts_path, "data-role" => "button", "class" => "ui-btn-left", "data-icon" => "home", "data-transition" => "reverse slide" %>
	<h1>Results</h1>
	<%= link_to 'About', about_path, "data-role" => "button", "class" => "ui-btn-right", "data-icon" => "info" %>
</div>

<div data-role="content">

  <div data-role="collapsible">
    <h2>Dataset</h2>
    All tweets contain a link to a scholarly article. Data collected by <%= link_to "altmetric.com", "http://altmetric.com" %>.

		<ul data-role="listview" data-theme="c" data-inset="true">
			<li>Posted <%= l @posts.first.published_at, :format => :twitter %> - <%= l @posts.last.published_at, :format => :result %></li>
			<li>Tweets <span class="ui-li-count"><%= @posts.count %></span></li>
			<li>Retweets <span class="ui-li-count"><%= @posts_with_rts.count %></li>
			<li>Tweets quoting article title<span class="ui-li-count"><%= @posts_with_title.count %></span></li>
			<li>Unique users <span class="ui-li-count"><%= @unique_author_count %></span></li>
			<li>Unique articles <span class="ui-li-count"><%= @unique_article_count %></span></li>
			<li>Unique journals <span class="ui-li-count"><%= @unique_journal_count %></span></li>
		</ul>
  </div>

	<div data-role="collapsible" data-collapsed="false">
	  <h2>Summary</h2>

	<%= pluralize(@ratings.count, 'classification') %> by <%= pluralize(@authors_with_ratings.count, 'user') %> for <%= pluralize(@posts_with_ratings.count, 'tweet') %> (<%= number_to_percentage(@posts_with_ratings.count * 100 / @posts.count, :precision => 0) %> of all tweets, <%= number_with_precision(Float(@ratings.count) / @posts_with_ratings.count, :precision => 1) %> ratings per tweet). <%= pluralize(@posts_with_spam.count, 'tweet') %> <%= @posts_with_spam.count == 1 ? "was" : "were" %> categorized as spam.
	
	  <h3>Subject Area</h3>
		<%= high_chart("topic", @topicchart) do |c| %>
			<%= "options.tooltip.formatter = function() { return this.y + ' Tweets: ' + (this.y / #{@posts_with_topic.count} * 100).toFixed(0) + '%'; }" %>
		<% end %>

		<h3>Agreement with Paper</h3>
		<%= high_chart("rhetoric", @rhetoricchart) do |c| %>
		  <%= "options.tooltip.formatter = function() { return this.y + ' Tweets: ' + (this.y / #{@posts_with_ratings.count} * 100).toFixed(0) + '%'; }" %>
		<% end %>

		<h3>Tweets by Author/Publisher</h3>
			<%= high_chart("author", @authorchart) do |c| %>
			  <%= "options.tooltip.formatter = function() { return this.y + ' Tweets: ' + (this.y / #{@posts_with_ratings.count} * 100).toFixed(0) + '%'; }" %>
		<% end %>

		<h3>Uses Methods/Data/Conclusions</h3>
		<%= high_chart("reuse", @reusechart) do |c| %>
		  <%= "options.tooltip.formatter = function() { return this.y + ' Tweets: ' + (this.y / #{@posts_with_ratings.count} * 100).toFixed(0) + '%'; }" %>
		<% end %>	
	</div>

	<div data-role="collapsible" data-collapsed="false">
	  <h2>Activity</h2>
	  <%= high_chart("activity", @activitychart) do |c| %>
	    <%= "options.tooltip.formatter = function() { return '<strong>' + Highcharts.dateFormat('%B %d, %Y', this.x + 7 * 3600 * 1000) + '</strong><br />' + this.y + ' Ratings'; }".html_safe %>
	  <% end %>
	</div>

	<div data-role="collapsible">	
	  <h2>Most active users</h2>

	  <% unless @authors.empty? %>
	  <ul data-role="listview" data-theme="c" data-inset="true">
		<% @authors.each do |author| %>
		  <li><%= link_to author.display_name, "http://twitter.com/#{author.username}" %>
		<span class="ui-li-count"><%= author.ratings_count.blank? ? 0 : author.ratings_count %></span>
	      	</li>
		<% end %>
		</ul>
	<% end %>
	</div>
</div>

app/views/ratings/new.mobile.erb
<div data-role="header">
	<h1>Classify Tweet</h1>
</div>

<div data-role="content" data-theme="c" class="new">
	<ul data-role="listview">
    <li><a href="<%= @post.article_url %>" rel="external" class="signed_in"><%= image_tag "http://api.twitter.com/1/users/profile_image/#{@post.author}" %>
    <h3><%= "@#{@post.author}" %></h3>
    <%= @post.body.html_safe  %>
    </a>
    </li>
  </ul>

  <div class="article_title">
    <% unless @post.article_title.blank? %>
      <%= @post.article_title_and_journal.html_safe %><p>
    <% end %>
  </div>

	  <% form_for @rating, :url => ratings_url do |form| %>
     <%= form.hidden_field :post_id, :value => @post.id %>
     <%= form.hidden_field :author_id, :value => current_author.id %>

		<fieldset data-role="controlgroup">
       <%= form.label :spam, "Spam" %>
       <%= check_box_tag "rating[spam]" %>
     </fieldset>

    <fieldset data-role="controlgroup">
	    <%= form.select :topic, topic_choices, { :prompt => 'Select Subject Area' } %>
    </fieldset>

		<fieldset data-role="controlgroup">
			<%= form.label "rhetoric_agreeswith", 'Agrees with paper' %>
			<%= form.radio_button("rhetoric", "agreesWith") %> 
			<%= form.label "rhetoric_discusses", 'Discusses paper' %>
			<%= form.radio_button("rhetoric", "discusses") %> 
			<%= form.label "rhetoric_disagreeswith", 'Disagrees with paper' %>
			<%= form.radio_button("rhetoric", "disagreesWith") %> 
		</fieldset>
		
		<fieldset data-role="controlgroup">	
			<%= form.label :is_author, "By paper author/publisher" %>
				<%= check_box_tag "rating[is_author]" %>
		</fieldset>
		
		<fieldset data-role="controlgroup">
			<%= form.label :method, 'Uses method from paper' %>
			<%= check_box_tag "rating[method]" %>
			<%= form.label :data, 'Uses data from paper' %>
			<%= check_box_tag "rating[data]" %>
			<%= form.label :conclusions, 'Uses conclusions from paper' %>
			<%= check_box_tag "rating[conclusions]" %>
	  </fieldset>
	
		<a href="<%= posts_path %>" data-role="button" data-icon="delete" data-inline="true" data-transition="reverse slide">Cancel</a>

			  <%= form.submit "Submit", "data-icon" => "check", "data-transition" => "reverse slide", "data-inline" => "true", "data-theme" => "b" %>
	<% end %>
</div>