config/routes.rb
# Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
# http://www.plos.org/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PlosAltMetrics::Application.routes.draw do
  resources :authors
  resources :ratings do
    collection do
      post 'update_spam'
    end
  end

  devise_for :authors, :controllers => { :omniauth_callbacks => "authors/omniauth_callbacks" } do
    get '/authors/auth/:provider' => 'authors/omniauth_callbacks#passthru'
    get 'sign_in', :to => 'authors/sessions#new', :as => :new_author_session
    match 'sign_out', :to => 'authors/sessions#destroy', :as => :destroy_author_session, :via => [:get, :delete]
  end
  
  resources :articles
  #match "/group/articles(/:id)(.:format)" => "groups#groupArticleSummaries"
  
  resources :groups
  resources :citations
  
  # Admin resources
  resources :sources
  resources :categories
  resources :authentications
  get '/docs(/:action)', :controller => :docs, :format => false
  
  get 'about', :to => 'index#index', :as => "about"
  
  # Authors are in default path, should therefore be defined after admin resources. 
  # Root goes to authors#index, needs to be defined.
  resources :posts, :path => "/"
  root :to => "posts#index"

end

app/models/category.rb
# $HeadURL$
# $Id$
#
# Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
# http://www.plos.org/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class Category < ActiveRecord::Base
  has_many :sources, :order => "sources.id"

end

app/controllers/categories_controller.rb
# Copyright (c) 2011 Martin Fenner
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class CategoriesController < ApplicationController
  before_filter :authenticate_author!

  #This is a way of excepting a list of DOIS and getting back summaries for them all.
  #Articles with no cites are not returned
  #This method does not check for article staleness and does not query articles for refresh
  def category_article_summaries
    logger.debug "categoryArticleSummaries"

    #Specifying multilple DOIS without a parameter proved nightmareish
    #So we do it here using a comma delimated list with format 
    #Specified as a parameter (ID)

    #Here sometimes the :format value may have a period attached to it
    #This will filter it out
    reqFormat = params[:format]

    if reqFormat != nil
      matchedFormat = reqFormat.match(/xml|csv|json/)
      
      #If we get a bad format, just default to nil (or HTML)
      if matchedFormat == nil
        request.format = nil
      else
        request.format = matchedFormat[0]
        logger.info "format:" + request.format
      end
    end

    logger.info "ID:" + params[:id]

    if !params[:id]
      raise "ID parameter not specified"
    end

    #Ids can be a collection
    ids = params[:id].split(',')
    ids = ids.map { |id| DOI::from_uri(id) }
      
    @result  = []

    # Specifiy the eager loading so we get all the data we need up front
    articles = Article.find(:all, 
      :include => [ :retrievals => [ :citations, { :source => :category } ]], 
      :conditions => [ "articles.doi in (?) and (retrievals.citations_count > 0 or retrievals.other_citations_count > 0)", ids ])
    
    @result = articles.map do |article|
      returning Hash.new do |hash|
        hash[:article] = article
        hash[:categorycounts] = article.citations_by_category
        
        # If any categories are specified via URL params, get those details
        hash[:categories] = params[:category].split(",").map do |category|
          sources = article.get_cites_by_category(category)
          { :name => category,
            :sources => sources } unless sources.empty?
        end.compact if params[:category]
      end
    end
  
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @result }
      format.json { render :json => @result, :callback => params[:callback] }
    end
  end

  # GET /categories
  def index
    @categories = Category.find(:all)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /categories/1
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /categories/new
  def new
    @category = Category.new
    
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        flash[:notice] = 'Category was successfully created.'
        format.html { redirect_to(categories_url) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # POST /categories/1
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        flash[:notice] = 'Category was successfully updated.'
        format.html { redirect_to(categories_url) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /categories/1
  def destroy
    @category = Category.find(params[:id])
    
    Source.find(:all, :conditions => {  :category_id => @category.id }).each do |s| 
      s.category = nil;
      s.save
    end
    
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
    end
  end

end

app/views/categories/_form.html.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
  # http://www.plos.org/
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<% category ||= form %>
<%= form_for(category) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :article_description %><br />
    <%= f.text_area :article_description, :size => "50x3" %>
  </p>

  <p>
    <%= f.label :author_description %><br />
    <%= f.text_area :author_description, :size => "50x3" %>
  </p>

  <p>
    <%= f.label :group_description %><br />
    <%= f.text_area :group_description, :size => "50x3" %>
  </p>

  <p>
    <%= f.submit(category.new_record? ? "Create" : "Update") %>
  </p>
<% end %>

app/views/categories/_index.html.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
  # http://www.plos.org/
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>

<h2>Categories <%= link_to image_tag("add.gif"), new_category_path %></h2>

Categories are a way to organize sources.  You can define a category for 
your sources by editing a source.

<ul>
<% for category in @categories %>
  <li>
    <h3><%= link_to h(category.name), category %></h3>
    <ul>
      <% category.sources.each do |source| %>
        <li><%= link_to h(source.name), source_path(source) %></li>
      <% end %>
    </ul>
  </li>
<% end %>
</ul>

app/views/categories/articles.html.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
  # http://www.plos.org/
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>

<div class="border">
<div class="page">
<h1>Article Summaries</h1>

<% for record in @result %>
  <div class="article">
    <span class="doi">
    <%=link_to h(record[:article].doi), article_path(record[:article]) %></h3>
    <span class="details">
      <ul>
      <% for groupcount in record[:groupcounts] %>
        <li><%=groupcount[:name] %>:
        <%=groupcount[:total] %></li>
      <% end %>
      </ul>
    </span>
  </div>
<% end %>
</div>
</div>

app/views/categories/edit.html.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
  # http://www.plos.org/
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<div class="border">
<div class="page">
<h1>Editing category "<%= @category.name %>"</h1>

<%= render :partial => "form", :object => @category %>

<%= link_to 'Show', category_path(@category) %>
<br/>
<%= link_to 'Back to list', categories_path %>
</div>
</div>

app/views/categories/groupArticleSummaries.html.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
  # http://www.plos.org/
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>

<div class="border">
<div class="page">

<h1>Article Summaries</h1>

<% for record in @result %>
  <div class="article">
    <span class="doi">
    <%=link_to h(record[:article].doi), article_path(record[:article]) %></h3>
    <span class="details">
      <ul>
      <% for groupcount in record[:groupcounts] %>
        <li><%=groupcount[:name] %>: <%=groupcount[:total] %><br/>
          <ul>
            <% for source in groupcount[:sources] %>
              <li><a href="<%=source[:public_url] %>"><%=source[:name] %> (<%=source[:total] %>)</a></li>
            <% end %>
          </ul>
        </li>
      <% end %>
      </ul>
    </span>
  </div>
<% end %>

</div>
</div>

app/views/categories/index.html.erb
<%#
  # Copyright (c) 2011 Martin Fenner
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<div id="index">
  <%= render :partial => 'index' %> 
</div>

app/views/categories/new.html.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
  # http://www.plos.org/
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<div class="border">
<div class="page">
<h1>Creating new category</h1>

<%= render :partial => "form", :object => @category %>

<%= link_to 'Back to list', categories_path %>
</div>
</div>

app/views/categories/show.html.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
  # http://www.plos.org/
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<div class="border">
<div class="page">
<h1>Details for <%=h @category.name %> </h1>

<p>
  <b>Name:</b>
  <%=h @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %>
<%= link_to 'Delete', category_path(@category), :confirm => 'Are you sure?', :method => :delete %>
</div>
</div>